In [55]:
import pandas as pd
import numpy as np
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

In [56]:
driver = webdriver.Chrome(r"C:\Users\Pooja.Mishra\Downloads\chromedriver_win32\chromedriver.exe")

In [3]:
url = 'https://www.amazon.com/Fire-HD-10/dp/B07KD6BTCZ/ref=sr_1_6?dchild=1&keywords=apple%2Btab&qid=1628535149&sr=8-6&th=1'
driver.get(url)

In [75]:
#click on reviews 
rating1_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 1star']")
rating1_button.click()

In [76]:
#creating empty list
Reviews_1=[]
Rating_1=[]
i=0
count = 0
while i<=3300:
    count=(len(Reviews_1))
    driver.refresh()
    #Scraping Reviews for Rating 1
    Rating_1_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_1_elements
    for i in Rating_1_elements:
        Rating_1.append(i.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_1_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for j in Reviews_1_elements:
        Reviews_1.append(j.text)
    count = len(Reviews_1)
    i = len(Reviews_1)
    if count<=3300:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [100]:
print (len(Reviews_1))
print (len(Rating_1))

3310
3310

In [101]:
#Storing Rating 1 Reviews in dataframe
R1 = pd.DataFrame({})
R1["Reviews_1"] = Reviews_1
R1["Rating_1"] = Rating_1
R1

                                              Reviews_1 Rating_1
0              Not faster than the previous generation.        1
1                                  Do Not But This Fire        1
2     Rubbish. Cannot add google play and all of the...        1
3                                          Buyer Beware        1
4              deletes books every night while charging        1
...                                                 ...      ...
3305  Where is the 64gb version without the annoying...        1
3306                     Technical difficulties persist        1
3307  Amazon should allow Android app store to downl...        1
3308                   Decent tablet, has tons of cons.        1
3309  Don’t buy if you want to use audible while rea...        1

[3310 rows x 2 columns]

In [8]:
#click on reviews 
rating2_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 2star']")
rating2_button.click()

In [50]:
#creating empty list
Reviews_2=[]
Rating_2=[]
i=0
count = 0
while i<=2000:
    count=(len(Reviews_2))
    driver.refresh()
    #Scraping Reviews for Rating 2
    Rating_2_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_2_elements
    for l in Rating_2_elements:
        Rating_2.append(l.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_2_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for k in Reviews_2_elements:
        Reviews_2.append(k.text)
    count = len(Reviews_2)
    i = len(Reviews_2)
    if count<=2000:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [51]:
#Storing Rating 1 Reviews in dataframe
R2 = pd.DataFrame({})
R2["Reviews_2"] = Reviews_2
R2["Rating_2"] = Rating_2
R2

                                              Reviews_2 Rating_2
0     Don’t pay the extra $15 for no ads, you will s...        2
1                               Just a few small quirks        2
2                                 Not a Friendly Device        2
3                              not like the old fire 8"        2
4     Books don't stay "saved" on the newest (9th ge...        2
...                                                 ...      ...
2005                             Difficult loading apps        2
2006                      Its a good item for the price        2
2007                                       Disappointed        2
2008              It does not play all games downloaded        2
2009                                          Not happy        2

[2010 rows x 2 columns]

In [52]:
#click on reviews 
rating3_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 3star']")
rating3_button.click()

In [57]:
#creating empty list
Reviews_3=[]
Rating_3=[]
i=0
count = 0
while i<=3550:
    count=(len(Reviews_3))
    driver.refresh()
    #Scraping Reviews for Rating 3
    Rating_3_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_3_elements
    for p in Rating_3_elements:
        Rating_3.append(p.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_3_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for m in Reviews_3_elements:
        Reviews_3.append(m.text)
    count = len(Reviews_3)
    i = len(Reviews_3)
    if count<=3550:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [58]:
print (len(Reviews_3))
print (len(Rating_3))

3556
3556

In [61]:
#Storing Rating 1 Reviews in dataframe
R3 = pd.DataFrame({})
R3["Reviews_3"] = Reviews_3
R3["Rating_3"] = Rating_3
R3

                                              Reviews_3 Rating_3
0                        10% battery drain when standby        3
1     Still disappointing for HDX owners, but is the...        3
2     Problem Resolved - My Review Was Apparently Ta...        3
3     Amazon updated the software so I'm updating my...        3
4                                      faster but...wtf        3
...                                                 ...      ...
3551                                great movie quality        3
3552                                            Awesome        3
3553                                not as good as ipad        3
3554                         Can't use many Google apps        3
3555  Moisture/ Liquid Detection icon would not disa...        3

[3556 rows x 2 columns]

In [62]:
#click on reviews 
rating4_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 4star']")
rating4_button.click()

In [68]:
#creating empty list
Reviews_4=[]
Rating_4=[]
i=0
count = 0
while i<=4500:
    count=(len(Reviews_4))
    driver.refresh()
    #Scraping Reviews for Rating 4
    Rating_4_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_4_elements
    for q in Rating_4_elements:
        Rating_4.append(q.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_4_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for r in Reviews_4_elements:
        Reviews_4.append(r.text)
    count = len(Reviews_4)
    i = len(Reviews_4)
    if count<=4500:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [69]:
print (len(Reviews_4))
print (len(Rating_4))

4510
4510

In [70]:
#Storing Rating 1 Reviews in dataframe
R4 = pd.DataFrame({})
R4["Reviews_4"] = Reviews_4
R4["Rating_4"] = Rating_4
R4

                                              Reviews_4 Rating_4
0                            Not going to blow smoke...        4
1     This is my 5th Kindle tablet, and my second 10...        4
2     Nice but deletes books. UPDATE: The issue has ...        4
3     Goodl tablet. Just a Warning on micro sd card ...        4
4     The most solid Kindle Fire hardware to date. S...        4
...                                                 ...      ...
4505                                    Worth the price        4
4506                                            quality        4
4507                                     Still confused        4
4508                                       Good quality        4
4509                               Good for light usage        4

[4510 rows x 2 columns]

In [71]:
#click on reviews 
rating5_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 5star']")
rating5_button.click()

In [72]:
#creating empty list
Reviews_5=[]
Rating_5=[]
i=0
count = 0
while i<=4500:
    count=(len(Reviews_5))
    driver.refresh()
    #Scraping Reviews for Rating 5
    Rating_5_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_5_elements
    for a in Rating_5_elements:
        Rating_5.append(a.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_5_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for b in Reviews_5_elements:
        Reviews_5.append(b.text)
    count = len(Reviews_5)
    i = len(Reviews_5)
    if count<=4500:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [73]:
print (len(Reviews_5))
print (len(Rating_5))

4510
4510

In [74]:
#Storing Rating 1 Reviews in dataframe
R5 = pd.DataFrame({})
R5["Reviews_5"] = Reviews_5
R5["Rating_5"] = Rating_5
R5

                                              Reviews_5 Rating_5
0     This tablet is the best 149 dollars, I've ever...        5
1                        Absolutely Perfect! I Love It!        5
2                 What is this flickering on my tablet?        5
3     Fantastic Tablet at this Price! Ignore the Hat...        5
4         Nothing even comes close at this price point!        5
...                                                 ...      ...
4505                                          Satisfied        5
4506                            Best tablet I’ve owned.        5
4507                                     so far so good        5
4508                         Battery Life Much Improved        5
4509                                      Great tablet!        5

[4510 rows x 2 columns]

# Reviews & Ratings for Laptop

In [3]:
laptop_url="https://www.amazon.com/Acer-A515-46-R14K-Quad-Core-Processor-Backlit/dp/B08VKNVDDR/ref=sr_1_3?dchild=1&keywords=laptop&qid=1628712307&sr=8-3&th=1"
driver.get(laptop_url)

In [93]:
#more reviews on Rating 1
more_reviews_1=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 1star']")
more_reviews_1.click()

In [ ]:
#creating empty list
Reviews_1_more=[]
Rating_1_more=[]
i=0
count = 0
while i<=628:
    count=(len(Reviews_1_more))
    driver.refresh()
    #Scraping rating for Rating 1
    Rating_1_more_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_1_elements
    for x in Rating_1_more_elements:
        Rating_1_more.append(x.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_1_more_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for y in Reviews_1_more_elements:
        Reviews_1_more.append(y.text)
    count = len(Reviews_1_more)
    i = len(Reviews_1_more)
    if count<=628:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [88]:
print (len(Reviews_1_more))
print (len(Rating_1_more))

10
10

In [96]:
#Storing Rating 1 Reviews in dataframe
R1_more_reviews = pd.DataFrame({})
R1_more_reviews["Reviews_1_more"] = Reviews_1_more
R1_more_reviews["Rating_1_more"] = Rating_1_more
R1_more_reviews

                                        Reviews_1_more Rating_1_more
0                      STAY AWAY from Microsoft 10S!!!             1
1                            Not a fan of this laptop.             1
2                                  Died the same night             1
3    Watch out for Microsoft glitch that prevents y...             1
4          Check the real price before buying in promo             1
..                                                 ...           ...
677                                          Great buy             1
678                                  Sound didn’t work             1
679                                          NOT happy             1
680                                                POS             1
681                    Dead on arrival. Does not work.             1

[682 rows x 2 columns]

In [ ]:
Rating_1_more

In [4]:
#reviews 2 More
rating2_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 2star']")
rating2_button.click()

In [6]:
#creating empty list
Reviews_2_more=[]
Rating_2_more=[]
i=0
count = 0
while i<=200:
    count=(len(Reviews_2_more))
    driver.refresh()
    #Scraping rating for Rating 2
    Rating_2_more_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_2_elements
    for e in Rating_2_more_elements:
        Rating_2_more.append(e.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_2_more_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for f in Reviews_2_more_elements:
        Reviews_2_more.append(f.text)
    count = len(Reviews_2_more)
    i = len(Reviews_2_more)
    if count<=200:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [8]:
print (len(Reviews_2_more))

210

In [9]:
#Storing Rating 1 Reviews in dataframe
R2_more_reviews = pd.DataFrame({})
R2_more_reviews["Reviews_2_more"] = Reviews_2_more
R2_more_reviews["Rating_2_more"] = Rating_2_more
R2_more_reviews

                                        Reviews_2_more Rating_2_more
0                                              Glitchy             2
1    Freezes often, and touchpad stopped working. W...             2
2    BUYER BEWARE...Problems with Touchpad and cras...             2
3                             Sounds like a jet engine             2
4                           Unable to Activate Windows             2
..                                                 ...           ...
205                                       Backlighting             2
206                              Wrong size advertised             2
207                                       Its okayy :(             2
208               Wrong description. Windows outdated.             2
209                              Disappointed customer             2

[210 rows x 2 columns]

In [10]:
#reviews 3 More
rating3_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 3star']")
rating3_button.click()

In [ ]:

Reviews_3_more=[]
Rating_3_more=[]
i=0
count = 0
while i<=328:
    count=(len(Reviews_3_more))
    driver.refresh()
    #Scraping rating for Rating 3
    Rating_3_more_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_3_elements
    for g in Rating_3_more_elements:
        Rating_3_more.append(g.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_3_more_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for h in Reviews_3_more_elements:
        Reviews_3_more.append(h.text)
    count = len(Reviews_3_more)
    i = len(Reviews_3_more)
    if count<=328:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [13]:
print (len(Reviews_3_more))

328

In [14]:
#Storing Rating 1 Reviews in dataframe
R3_more_reviews = pd.DataFrame({})
R3_more_reviews["Reviews_3_more"] = Reviews_3_more
R3_more_reviews["Rating_3_more"] = Rating_3_more
R3_more_reviews

                                        Reviews_3_more Rating_3_more
0              Only has 3gb of RAM. Acer lied. Beware.             3
1    Good Price Point for a Decent Laptop - Updated...             3
2    Bloatware. Forced MS Accounts. Nonsense "S Mod...             3
3                  Beautiful but Windows 10s spoils it             3
4                   Worked Great Until Windows updated             3
..                                                 ...           ...
323                   Win 10 s is kind of inconvenient             3
324                                             Volume             3
325               Beautiful & Fast but can be UNSTABLE             3
326                                              Sleek             3
327                   Start being slow after half year             3

[328 rows x 2 columns]

In [ ]:
#Collecting more reviews for critical Rating

# Reviews on Television

In [17]:
tel_url = 'https://www.amazon.com/product-reviews/B07F981R8M/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=one_star&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar'
driver.get(tel_url)

In [18]:
#click at Rating 1
tv_Rating_1_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 1star']")
tv_Rating_1_button.click()

In [19]:
#creating empty list
Reviews_1_tv=[]
Rating_1_tv=[]
i=0
count = 0
while i<=600:
    count=(len(Reviews_1_tv))
    driver.refresh()
    #Scraping rating for Rating 1
    Rating_1_tv_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_1_elements
    for s in Rating_1_tv_elements:
        Rating_1_tv.append(s.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_1_tv_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for y in Reviews_1_tv_elements:
        Reviews_1_tv.append(y.text)
    count = len(Reviews_1_tv)
    i = len(Reviews_1_tv)
    if count<=600:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [20]:
#Storing Rating 1 Reviews in dataframe
Rating_1_tv = pd.DataFrame({})
Rating_1_tv["Reviews_1_more"] = Reviews_1_tv
Rating_1_tv["Rating_1_more"] = Rating_1_tv
Rating_1_tv

,Reviews_1_more,Rating_1_more
0,TRASH. WiFi doesn't work.,TRASH. WiFi doesn't work.
1,TCL Roku TVs are great! But...,TCL Roku TVs are great! But...
2,Strong Arm Sales To Purchase Roku Channels!! B...,Strong Arm Sales To Purchase Roku Channels!! B...
3,"Three units, all defective. Do not buy.","Three units, all defective. Do not buy."
4,Did not work!,Did not work!
...,...,...
605,arrived broken,arrived broken
606,Garbage,Garbage
607,Shattered screen in transit,Shattered screen in transit
608,Remote is worthless,Remote is worthless
609,TCL sucks,TCL sucks

In [21]:
#click at Rating 1
tv_Rating_2_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 2star']")
tv_Rating_2_button.click()

In [22]:
#creating empty list
Reviews_2_tv=[]
Rating_2_tv=[]
i=0
count = 0
while i<=490:
    count=(len(Reviews_2_tv))
    driver.refresh()
    #Scraping rating for Rating 2
    Rating_2_tv_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_2_elements
    for s in Rating_2_tv_elements:
        Rating_2_tv.append(s.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_2_tv_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for y in Reviews_2_tv_elements:
        Reviews_2_tv.append(y.text)
    count = len(Reviews_2_tv)
    i = len(Reviews_2_tv)
    if count<=490:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [23]:
#Storing Rating 1 Reviews in dataframe
Rating_2_tv = pd.DataFrame({})
Rating_2_tv["Reviews_2_more"] = Reviews_2_tv
Rating_2_tv["Rating_2_more"] = Rating_2_tv
Rating_2_tv

,Reviews_2_more,Rating_2_more
0,Netflix hangs on this TV,Netflix hangs on this TV
1,"remote control poorly design, lacks basic funt...","remote control poorly design, lacks basic funt..."
2,Two busts!,Two busts!
3,Remote is Trash,Remote is Trash
4,When it works it's great,When it works it's great
...,...,...
487,Not a normal tv or remote. But great for some ...,Not a normal tv or remote. But great for some ...
488,Get What You Pay For,Get What You Pay For
489,Annoying,Annoying
490,Sound cuts in snd out,Sound cuts in snd out
491,Won’t detect WiFi or hotspot-broken!!,Won’t detect WiFi or hotspot-broken!!

In [24]:
#click at Rating 1
tv_Rating_3_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 3star']")
tv_Rating_3_button.click()

In [25]:
#creating empty list
Reviews_3_tv=[]
Rating_3_tv=[]
i=0
count = 0
while i<=570:
    count=(len(Reviews_3_tv))
    driver.refresh()
    #Scraping rating for Rating 3
    Rating_3_tv_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_3_elements
    for c in Rating_3_tv_elements:
        Rating_3_tv.append(c.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_3_tv_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for d in Reviews_3_tv_elements:
        Reviews_3_tv.append(d.text)
    count = len(Reviews_3_tv)
    i = len(Reviews_3_tv)
    if count<=570:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [26]:
#Storing Rating 1 Reviews in dataframe
Rating_3_tv = pd.DataFrame({})
Rating_3_tv["Reviews_3_more"] = Reviews_3_tv
Rating_3_tv["Rating_3_more"] = Rating_3_tv
Rating_3_tv

,Reviews_3_more,Rating_3_more
0,Decent TV,Decent TV
1,Issues,Issues
2,The screen glows at night! (in a pitch black r...,The screen glows at night! (in a pitch black r...
3,Not worth it,Not worth it
4,*No wired ethernet* on this model,*No wired ethernet* on this model
...,...,...
567,You get what you pay for,You get what you pay for
568,The remote is important,The remote is important
569,Great pictures,Great pictures
570,Replacement,Replacement
571,Remote down button useless,Remote down button useless

In [29]:
tel_1080url = 'https://www.amazon.com/TCL-32S327-32-Inch-1080p-Smart/dp/B07F981R8M/ref=pd_sbs_1/135-1733646-4020219?pd_rd_w=v8kRP&pf_rd_p=3676f086-9496-4fd7-8490-77cf7f43f846&pf_rd_r=4C5SSAW1QWN4ZWMB2F98&pd_rd_r=acb0a330-79d0-41c1-bc18-98e14dc623ae&pd_rd_wg=5X4tC&pd_rd_i=B07F981R8M&psc=1'
driver.get(tel_1080url)

In [30]:
#click at Rating 1
tv_1Rating_1_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 1star']")
tv_1Rating_1_button.click()

In [38]:
#creating empty list
Reviews_1_tv1080=[]
Rating_1_tv1080=[]
i=0
count = 0
while i<=600:
    count=(len(Reviews_1_tv1080))
    driver.refresh()
    #Scraping rating for Rating 1
    Rating_1_tv_1080elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_1_elements
    for s in Rating_1_tv_1080elements:
        Rating_1_tv1080.append(s.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_1_tv_1080elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for y in Reviews_1_tv_1080elements:
        Reviews_1_tv1080.append(y.text)
    count = len(Reviews_1_tv1080)
    i = len(Reviews_1_tv1080)
    if count<=600:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [39]:
print (len(Reviews_1_tv1080))
print (len(Rating_1_tv1080))

610
610

In [40]:
#Storing Rating 1 Reviews in dataframe
R5 = pd.DataFrame({})
R5["Reviews_1_more"] = Reviews_1_tv1080
R5["Rating_1_more"] = Rating_1_tv1080
R5

                                        Reviews_1_more Rating_1_more
0                            TRASH. WiFi doesn't work.             1
1                       TCL Roku TVs are great! But...             1
2    Strong Arm Sales To Purchase Roku Channels!! B...             1
3              Three units, all defective. Do not buy.             1
4                                        Did not work!             1
..                                                 ...           ...
605                                     arrived broken             1
606                                            Garbage             1
607                        Shattered screen in transit             1
608                                Remote is worthless             1
609                                          TCL sucks             1

[610 rows x 2 columns]

In [41]:
#click at Rating 1
tv1080_Rating_2_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 2star']")
tv1080_Rating_2_button.click()

In [46]:
#creating empty list
Reviews_2_tv1080=[]
Rating_2_tv1080=[]
i=0
count = 0
while i<=490:
    count=(len(Reviews_2_tv1080))
    driver.refresh()
    #Scraping rating for Rating 2
    Rating_2_tv1080_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_2_elements
    for u in Rating_2_tv1080_elements:
        Rating_2_tv1080.append(u.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_2_tv1080_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for v in Reviews_2_tv1080_elements:
        Reviews_2_tv1080.append(v.text)
    count = len(Reviews_2_tv1080)
    i = len(Reviews_2_tv1080)
    if count<=490:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [48]:
#Storing Rating 1 Reviews in dataframe
R6 = pd.DataFrame({})
R6["Reviews_2_more"] = Reviews_2_tv1080
R6["Rating_2_more"] = Rating_2_tv1080
R6

                                        Reviews_2_more Rating_2_more
0                             Netflix hangs on this TV             2
1    remote control poorly design, lacks basic funt...             2
2                                           Two busts!             2
3                                      Remote is Trash             2
4                             When it works it's great             2
..                                                 ...           ...
487  Not a normal tv or remote. But great for some ...             2
488                               Get What You Pay For             2
489                                           Annoying             2
490                              Sound cuts in snd out             2
491              Won’t detect WiFi or hotspot-broken!!             2

[492 rows x 2 columns]

In [49]:
#click at Rating 1
tv_Rating_3_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 3star']")
tv_Rating_3_button.click()

In [53]:
#creating empty list
Reviews_3_tv1080=[]
Rating_3_tv1080=[]
i=0
count = 0
while i<=500:
    count=(len(Reviews_3_tv))
    driver.refresh()
    #Scraping rating for Rating 3
    Rating_3_tv1080_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_3_elements
    for q in Rating_3_tv1080_elements:
        Rating_3_tv1080.append(q.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_3_tv1080_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for r in Reviews_3_tv1080_elements:
        Reviews_3_tv1080.append(r.text)
    count = len(Reviews_3_tv1080)
    i = len(Reviews_3_tv1080)
    if count<=500:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [54]:
#Storing Rating 1 Reviews in dataframe
R7 = pd.DataFrame({})
R7["Reviews_3_more"] = Reviews_3_tv1080
R7["Rating_3_more"] = Rating_3_tv1080
R7

                                        Reviews_3_more Rating_3_more
0                                            Decent TV             3
1                                               Issues             3
2    The screen glows at night! (in a pitch black r...             3
3                                         Not worth it             3
4                    *No wired ethernet* on this model             3
..                                                 ...           ...
505  OK TV overall from TCL for just under $130. Ge...             3
506            Mostly Satisfied except one major issue             3
507       Nice TV But Terrible Remote Control Receiver             3
508                                      Not impressed             3
509                      The remote control is useless             3

[510 rows x 2 columns]

In [ ]:
rating2_url=https://www.amazon.com/Fire-HD-8-tablet/dp/B07TMJ1R3X/ref=p13n_ds_purchase_sim_1p_dp_desktop_6/135-1733646-4020219?pd_rd_w=myXoh&pf_rd_p=a1e2cc28-dc94-4535-bc22-27c603bb8fa2&pf_rd_r=AKJCGK6FRDVTWHWPK6XK&pd_rd_r=b601e7f7-61a0-4692-a40c-994e1c5c4684&pd_rd_wg=qSuH1&pd_rd_i=B07TMJ1R3X&psc=1

In [57]:
amazon_url = 'https://www.amazon.com/Fire-HD-8-tablet/dp/B07TMJ1R3X/ref=p13n_ds_purchase_sim_1p_dp_desktop_6/135-1733646-4020219?pd_rd_w=myXoh&pf_rd_p=a1e2cc28-dc94-4535-bc22-27c603bb8fa2&pf_rd_r=AKJCGK6FRDVTWHWPK6XK&pd_rd_r=b601e7f7-61a0-4692-a40c-994e1c5c4684&pd_rd_wg=qSuH1&pd_rd_i=B07TMJ1R3X&psc=1'
driver.get(amazon_url)

In [58]:
#click at Rating 1
amazon_Rating_2_button=driver.find_element_by_xpath("//td[@class='aok-nowrap']/span/a[@class='a-link-normal 2star']")
amazon_Rating_2_button.click()

In [62]:
#creating empty list
Reviews_2_amazon=[]
Rating_2_amazon=[]
i=0
count = 0
while i<=910:
    count=(len(Reviews_2_amazon))
    driver.refresh()
    #Scraping rating for Rating 2
    Rating_2_amazon_elements=driver.find_elements_by_xpath(".//div[@class='a-row']/a/i/span[@class='a-icon-alt']")
    #Rating_2_elements
    for u in Rating_2_amazon_elements:
        Rating_2_amazon.append(u.get_attribute("innerHTML").strip().split('.')[0].strip())
    Reviews_2_amazon_elements=driver.find_elements_by_xpath("//div[@class='a-row']/a[@class='a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold']")
    for v in Reviews_2_amazon_elements:
        Reviews_2_amazon.append(v.text)
    count = len(Reviews_2_amazon)
    i = len(Reviews_2_amazon)
    if count<=910:
        nextpage=driver.find_element_by_xpath("//ul[@class='a-pagination']/li[@class='a-last']/a")
        nextpage.click()
        time.sleep(3)

In [63]:
#Storing Rating 1 Reviews in dataframe
R8 = pd.DataFrame({})
R8["Reviews_2_more"] = Reviews_2_amazon
R8["Rating_2_more"] = Rating_2_amazon
R8

                                        Reviews_2_more Rating_2_more
0    Trying to remain optimistic... - Update #2 is ...             2
1              Plenty of issues, screen, software etc.             2
2                                    Major Amazon Fail             2
3                        Nothing like what I hoped for             2
4                    Seriously considering an exchange             2
..                                                 ...           ...
908                                               junk             2
909                                          El precio             2
910             It's not soo great.. but.. it's ''ok''             2
911                                        small print             2
912                             Love hate relationship             2

[913 rows x 2 columns]

In [74]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('Ecommerce_Data2.xlsx', engine='xlsxwriter')

In [75]:
# Write each dataframe to a different worksheet.
Rating_2_tv.to_excel(writer, sheet_name='Sheet1')
Rating_1_tv.to_excel(writer, sheet_name='Sheet2')
R7.to_excel(writer, sheet_name='Sheet3')
R8.to_excel(writer, sheet_name='Sheet4')
R2_more_reviews.to_excel(writer, sheet_name='Sheet5')
Rating_3_tv.to_excel(writer, sheet_name='Sheet6')
R5.to_excel(writer, sheet_name='Sheet7')
R6.to_excel(writer, sheet_name='Sheet8')
R3_more_reviews.to_excel(writer, sheet_name='Sheet9')

In [71]:
R3_more_reviews.to_excel(writer, sheet_name='Sheet1')

In [76]:
writer.save()

# Conclusion: In this jupyter file, we have collected 22500 entries for Reviews and Rating between 1 to 5 including 4500 each. Dataset comprises of ratings from consumers for electronics products.